"""Hand-built Zstandard frames that contain real RLE blocks.

libzstd does not emit `Block_Type = RLE` for any input in the main corpus, so a
decoder can mis-frame RLE blocks and still pass every generated vector. An RLE
block header carries the *regenerated* length while its body is a single byte,
which is exactly the kind of asymmetry a decoder gets wrong silently.

Every frame here is checked against the reference decompressor before it is
written, so these stay conformance vectors rather than guesses about the format.
"""
import hashlib
import json
import os
import struct
import sys

import zstandard

OUT = sys.argv[1]
os.makedirs(OUT, exist_ok=True)

MAGIC = 0xFD2FB528
RAW, RLE = 0, 1


def block(last, kind, size, body):
    header = (size << 3) | (kind << 1) | (1 if last else 0)
    return struct.pack("<I", header)[:3] + body


def frame(blocks, content_size=None, window_log=None, checksum=None):
    descriptor = 0
    fields = b""
    if content_size is not None and window_log is None:
        descriptor |= 0x20  # Single_Segment_Flag: window is the content size
        if content_size < 256:
            descriptor |= 0x00
            fields = struct.pack("<B", content_size)
        elif content_size < 65536 + 256:
            descriptor |= 0x40
            fields = struct.pack("<H", content_size - 256)
        else:
            descriptor |= 0x80
            fields = struct.pack("<I", content_size)
    else:
        exponent = window_log - 10
        fields = struct.pack("<B", exponent << 3)
    if checksum is not None:
        descriptor |= 0x04
    body = struct.pack("<I", MAGIC) + struct.pack("<B", descriptor) + fields
    body += b"".join(blocks)
    if checksum is not None:
        body += struct.pack("<I", checksum)
    return body


manifest = []


def emit(name, raw, compressed, note):
    decoded = zstandard.ZstdDecompressor().decompress(
        compressed, max_output_size=1 << 24
    )
    assert decoded == raw, f"{name}: reference decoder disagrees"
    entry = {
        "name": name,
        "note": note,
        "rawBytes": len(raw),
        "compressedBytes": len(compressed),
        "rawSha256": hashlib.sha256(raw).hexdigest(),
        "hasRawFile": len(raw) <= 4096,
    }
    if entry["hasRawFile"]:
        open(os.path.join(OUT, name + ".raw"), "wb").write(raw)
    open(os.path.join(OUT, name + ".zst"), "wb").write(compressed)
    manifest.append(entry)


# A single RLE block: the case that breaks a decoder which reads Block_Size
# bytes of body.
raw = b"\x5a" * 900
emit(
    "rle-block-single",
    raw,
    frame([block(True, RLE, len(raw), b"\x5a")], content_size=len(raw)),
    "one RLE block, body is a single byte",
)

# The largest regenerated size a single block may declare.
raw = b"\x41" * (128 * 1024)
emit(
    "rle-block-max",
    raw,
    frame([block(True, RLE, len(raw), b"\x41")], content_size=len(raw)),
    "RLE block at the 128 KiB block maximum",
)

# RLE interleaved with raw blocks: a decoder that mis-advances the cursor after
# the RLE block corrupts everything that follows instead of failing cleanly.
head = b"flucord-head"
tail = b"flucord-tail"
run = b"\x7f" * 5000
raw = head + run + tail
emit(
    "rle-block-mixed",
    raw,
    frame(
        [
            block(False, RAW, len(head), head),
            block(False, RLE, len(run), b"\x7f"),
            block(True, RAW, len(tail), tail),
        ],
        content_size=len(raw),
    ),
    "raw, RLE and raw blocks in one frame",
)

# Many small RLE blocks behind a declared window: this is the shape that made
# an unamortized window compaction quadratic.
runs = [bytes([index % 251]) * 64 for index in range(600)]
raw = b"".join(runs)
emit(
    "rle-block-storm",
    raw,
    frame(
        [
            block(index == len(runs) - 1, RLE, len(part), part[:1])
            for index, part in enumerate(runs)
        ],
        window_log=10,
    ),
    "600 RLE blocks against a 1 KiB window",
)

# RLE plus a content checksum, so the hash has to run over regenerated bytes
# rather than over the frame body.
raw = b"\x11" * 4096
emit(
    "rle-block-checksum",
    raw,
    frame(
        [block(True, RLE, len(raw), b"\x11")],
        content_size=len(raw),
        checksum=zstandard.ZstdCompressor(write_checksum=True)
        and struct.unpack(
            "<I",
            zstandard.ZstdCompressor(write_checksum=True).compress(raw)[-4:],
        )[0],
    ),
    "RLE block followed by an xxh64 content checksum",
)

# A full window rebuilt out of RLE blocks, then thousands of one-byte blocks.
# This is the shape that makes an unamortized window compaction quadratic: the
# tail adds 0.07% more input but used to cost hundreds of times the work.
fill = b"a" * (128 * 1024)
tail_runs = [b"b"] * 3000
raw = fill * 33 + b"".join(tail_runs)
emit(
    "rle-block-window-storm",
    raw,
    frame(
        [block(False, RLE, len(fill), b"a") for _ in range(33)]
        + [block(index == len(tail_runs) - 1, RLE, 1, b"b")
           for index in range(len(tail_runs))],
        window_log=22,
    ),
    "4 MiB window refilled by RLE blocks then 3000 one-byte blocks",
)

json.dump(manifest, open(os.path.join(OUT, "manifest-rle.json"), "w"), indent=2)
print("rle vectors=%d" % len(manifest))
