import 'dart:typed_data';

import 'zstd_error.dart';
import 'zstd_huffman.dart';
import 'zstd_tables.dart';

/// A decoded literals section: the bytes, how much of the block it ate, and the
/// Huffman table the next block may inherit.
typedef ZstdLiterals = ({
  Uint8List data,
  int bytesRead,
  ZstdHuffmanTable? table,
});

/// Decodes the literals section that opens a compressed block.
///
/// [previous] is the Huffman table left over from an earlier block in the same
/// frame. A Treeless_Literals_Block is how an encoder says "the tree has not
/// changed", which is common on a Gateway stream where every dispatch shares
/// the same JSON alphabet.
ZstdLiterals readZstdLiterals(
  Uint8List block,
  int start,
  int end,
  ZstdHuffmanTable? previous,
) {
  if (start >= end) {
    zstdFail('Compressed block has no literals section', start);
  }
  final head = block[start];
  final type = head & 0x03;
  final sizeFormat = (head >> 2) & 0x03;

  if (type == 0 || type == 1) {
    final int regenerated;
    final int headerSize;
    switch (sizeFormat) {
      case 1:
        _require(start, end, 2);
        regenerated = (head >> 4) | (block[start + 1] << 4);
        headerSize = 2;
      case 3:
        _require(start, end, 3);
        regenerated =
            (head >> 4) | (block[start + 1] << 4) | (block[start + 2] << 12);
        headerSize = 3;
      default:
        regenerated = head >> 3;
        headerSize = 1;
    }
    if (regenerated > zstdMaxBlockSize) {
      zstdFail('Literals section claims $regenerated bytes', start);
    }
    if (type == 0) {
      _require(start, end, headerSize + regenerated);
      return (
        data: Uint8List.sublistView(
          block,
          start + headerSize,
          start + headerSize + regenerated,
        ),
        bytesRead: headerSize + regenerated,
        table: previous,
      );
    }
    _require(start, end, headerSize + 1);
    return (
      data: Uint8List(regenerated)
        ..fillRange(0, regenerated, block[start + headerSize]),
      bytesRead: headerSize + 1,
      table: previous,
    );
  }

  // Huffman coded, with or without a tree description in front of it.
  final int headerSize;
  switch (sizeFormat) {
    case 2:
      headerSize = 4;
    case 3:
      headerSize = 5;
    default:
      headerSize = 3;
  }
  _require(start, end, headerSize);
  var packed = 0;
  for (var index = 0; index < headerSize; index++) {
    packed |= block[start + index] << (8 * index);
  }
  final int regenerated;
  final int compressed;
  switch (headerSize) {
    case 4:
      regenerated = (packed >> 4) & 0x3fff;
      compressed = (packed >> 18) & 0x3fff;
    case 5:
      regenerated = (packed >> 4) & 0x3ffff;
      compressed = (packed >> 22) & 0x3ffff;
    default:
      regenerated = (packed >> 4) & 0x3ff;
      compressed = (packed >> 14) & 0x3ff;
  }
  if (regenerated > zstdMaxBlockSize) {
    zstdFail('Literals section claims $regenerated bytes', start);
  }
  _require(start, end, headerSize + compressed);

  final sectionStart = start + headerSize;
  final sectionEnd = sectionStart + compressed;
  var streamStart = sectionStart;
  final ZstdHuffmanTable table;
  if (type == 2) {
    final tree = readZstdHuffmanTable(block, sectionStart, sectionEnd);
    table = tree.table;
    streamStart += tree.bytesRead;
  } else {
    final inherited = previous;
    if (inherited == null) {
      zstdFail('Treeless literals arrived before any Huffman tree', start);
    }
    table = inherited;
  }

  final data = Uint8List(regenerated);
  if (regenerated > 0) {
    // Size_Format 0 is the only single stream spelling; the others split the
    // literals into four independently decodable quarters.
    if (sizeFormat == 0) {
      decodeZstdHuffmanStream(
        table,
        block,
        streamStart,
        sectionEnd,
        data,
        0,
        regenerated,
      );
    } else {
      decodeZstdHuffmanStreams(
        table,
        block,
        streamStart,
        sectionEnd,
        data,
        regenerated,
      );
    }
  }
  return (data: data, bytesRead: headerSize + compressed, table: table);
}

void _require(int start, int end, int length) {
  if (start + length > end) {
    zstdFail('Literals section runs past the end of its block', start);
  }
}
